name: Branch checks
description: Action to run branch checks for code consistency

runs:
  using: composite
  steps:
    - name: Check Formatting
      shell: bash
      run: pnpm format:check

    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Typecheck
      shell: bash
      run: pnpm typecheck

    # Add additional branch checks here.
    # i.e. Tests, Translations, security, and any other additional checks.
