// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
  body1: '1rem',
  body2: '0.875rem',
  caption1: '0.75rem',
  caption2: '0.6875rem',
  display1: '3rem',
  h1: '2.125rem',
  h2: '1.5rem',
  h3: '1.25rem',
  h4: '1rem',
  h5: '0.875rem',
} as const;

export default fontSizes;
