// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
  '0': '0em',
  '01': '0.0063em',
  '015': '0.0094em',
  '025': '0.0156em',
  '05': '0.0313em',
} as const;

export default letterSpacings;
